#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ACTIVE_PAGES = ("CI", "RP", "SD", "LR", "SI", "DM", "NR", "AE", "LB", "DG", "DH")
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "crates/services/web-server/tests/api/case_editor_contract/generated"
)


def load_contract(registry_root: Path, page_id: str) -> dict:
    path = registry_root / "editor-contracts" / f"{page_id.lower()}.json"
    contract = json.loads(path.read_text(encoding="utf-8"))
    if contract.get("pageId") != page_id:
        raise ValueError(f"{path}: expected pageId {page_id}")
    return contract


def test_name(code: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", code.lower()).strip("_")
    if not normalized:
        raise ValueError(f"cannot generate test name for {code!r}")
    if normalized[0].isdigit():
        normalized = f"field_{normalized}"
    return normalized


def render_page(page_id: str, fields: list[dict]) -> str:
    declarations = []
    names = set()
    for field in sorted(fields, key=lambda item: item["code"]):
        name = test_name(field["code"])
        if name in names:
            raise ValueError(f"duplicate generated test name {name} in {page_id}")
        names.add(name)
        declarations.append(
            f'field_contract_test!({name}, "{field["code"]}");'
        )
    body = "\n".join(declarations)
    return (
        "// @generated by registry/tools/generate_editor_contract_web_tests.py.\n"
        "// Do not edit by hand.\n\n"
        f"{body}\n"
    )


def generate(registry_root: Path, output_root: Path) -> dict[str, str]:
    outputs = {}
    output_root.mkdir(parents=True, exist_ok=True)
    for page_id in ACTIVE_PAGES:
        contract = load_contract(registry_root, page_id)
        rendered = render_page(page_id, contract["fields"])
        outputs[page_id] = rendered
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    outputs = generate(REPO_ROOT / "registry", DEFAULT_OUTPUT)
    stale = []
    for page_id, rendered in outputs.items():
        path = DEFAULT_OUTPUT / f"{page_id.lower()}_fields.rs"
        if args.write:
            path.write_text(rendered, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != rendered:
            stale.append(str(path.relative_to(REPO_ROOT)))
    if stale:
        print("generated editor contract tests are stale; run with --write")
        for path in stale:
            print(path)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
